# Implementation of the Yggdrasil Distribute API using TensorFlow Distribution Strategies.
#

package(
    default_visibility = ["//visibility:public"],
    licenses = ["notice"],
)

# Worker binaries
# ===============
